### ISSUE TITLE
Not python3 compatible

### ISSUE THREAD

**Issue by jvlomax** [dvx/lofi#4]
Trying to run the application on windows using python3 fails the build.

```
$ node-gyp rebuild --target=4.0.1 --arch=x64 --dist-url=https://atom.io/download/electron
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.15.0 | win32 | x64
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\north\AppData\Local\Programs\Python\Python36\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\north\\git\\lofi\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=4.0.1" "--arch=x64" "--dist-url=https://atom.io/download/electron"
gyp ERR! cwd C:\Users\north\git\lofi
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command
```

This is because the install doesn't support python3.

I've tried looking around where the issue is so I can fix it, but it looks like it's an issue with node-gyp? Is there a workaround for this?

**Comment by szepnapot** [comment]
Yes, it's due to `node-gyp`, and sadly it looks like they do not plan to add python 3 support in the near future.

https://github.com/nodejs/node-gyp#on-unix
https://github.com/nodejs/node-gyp/issues/1337

**Comment by nitrocode** [comment]
This is worth reopening since node-gyp supports python 3.x now

@dvx
